import React from "react";
import type { ToolDefinition } from "../../core/types.ts";

export const tool: ToolDefinition = {
  id: "linux-command",
  name: { zh: "Linux 命令助手", en: "Linux Command Helper" },
  description: { zh: "常用 Linux 命令速查与示例", en: "Search common Linux commands and examples" },
  category: "other",
  icon: "🐧",
  keywords: ["linux", "shell", "bash", "command", "terminal", "命令", "脚本", "运维"],
  type: "builtin",
  i18n: {
    zh: {
      title: "Linux 命令速查",
      hint: "搜索命令、用途或示例",
      localTab: "本地速查",
      onlineTab: "在线查询",
      search: "搜索命令，例如 find、日志、网络...",
      empty: "没有匹配的命令",
      onlineHint: "数据来源：tldr-pages（GitHub）。只查询命令名，不会执行命令。",
      onlinePlaceholder: "输入命令名，例如 systemctl",
      onlineSearch: "查询",
      onlineLoading: "查询中...",
      onlineResult: "在线文档",
      onlineSource: "在 GitHub 查看来源",
      onlineInvalid: "请输入单个命令名，例如 grep 或 systemctl",
      onlineNotFound: "未找到该命令的在线文档",
      onlineNetworkError: "网络请求失败，请检查网络连接",
      onlineFailed: "在线查询失败",
      syntaxTitle: "语法",
      examplesTitle: "示例",
      "category.all": "全部",
      "category.files": "文件与目录",
      "category.text": "文本处理",
      "category.system": "系统与进程",
      "category.network": "网络",
      "category.permissions": "权限",
    },
    en: {
      title: "Linux command reference",
      hint: "Search commands, use cases, or examples",
      localTab: "Local reference",
      onlineTab: "Online lookup",
      search: "Search commands, e.g. find, logs, network...",
      empty: "No matching commands",
      onlineHint:
        "Source: tldr-pages (GitHub). Only the command name is queried; nothing is executed.",
      onlinePlaceholder: "Enter a command name, e.g. systemctl",
      onlineSearch: "Search",
      onlineLoading: "Loading...",
      onlineResult: "Online documentation",
      onlineSource: "View source on GitHub",
      onlineInvalid: "Enter one command name, such as grep or systemctl",
      onlineNotFound: "No online documentation found for this command",
      onlineNetworkError: "Network request failed; check your connection",
      onlineFailed: "Online lookup failed",
      syntaxTitle: "Syntax",
      examplesTitle: "Examples",
      "category.all": "All",
      "category.files": "Files & directories",
      "category.text": "Text processing",
      "category.system": "System & processes",
      "category.network": "Network",
      "category.permissions": "Permissions",
    },
  },
  component: React.lazy(() =>
    import("./LinuxCommands.tsx").then((m) => ({ default: m.LinuxCommandsTool }))
  ),
};
